import os

SQLALCHEMY_DATABASE_URI=os.environ.get('SQLALCHEMY_DATABASE_URI')
SECRET_KEY=os.environ.get('SECRET_KEY')
SQLALCHEMY_TRACK_MODIFICATIONS=False
USER_NAME=os.environ.get('USER_NAME')
PASSWORD_EMAIL=os.environ.get('PASSWORD_EMAIL')